// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldhcfrpobkqopccrjveu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkaGNmcnBvYmtxb3BjY3JqdmV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MzI2MzksImV4cCI6MjA3MDIwODYzOX0.7zZNIioKHC2iJeKiFejzKewxkpbkiPfM1OplyjXwwj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});